version: "3.1"

services:
  web:
    image: gradle:4.0.1-jdk8
    volumes:
      - .:/usr/src/my-orders-spring-boot
    working_dir: "/usr/src/my-orders-spring-boot"
    command: bash -c "gradle build && java -jar build/libs/my-orders-spring-boot-docker-0.1.0.jar"
    ports:
      - "8080:8080"